### ISSUE TITLE
Author List Extends Past Right Margin

### ISSUE THREAD

**Issue by ezbc** [caverac/agd-doc#16]
The author list extends past the right margin.

The authors are defined in conf.py within the list `latex_documents` on [line 205](https://github.com/caverac/agd-doc/blob/4c580c14dd7890006a423e5e27e2eddb6330b89b/conf.py#L205).

I have tried using '\n' between Claire Murray and Elijah Bernstein-Cooper but this did not work.

**Comment by caverac** [comment]
Changed to initials R. Lindner, ... I think this a better option than breaking the line
