### ISSUE TITLE
Guassian Function in Terms of FWHM

### ISSUE THREAD

**Issue by ezbc** [caverac/agd-doc#2]
In section 3.1.1 we need to confirm the Gaussian function description in terms of FWHM.

See the Wolfram description:
http://mathworld.wolfram.com/GaussianFunction.html

**Comment by caverac** [comment]
I still think there's a problem with the equation in the python code. If you use 

FWHM = 2.355 sigma

then the function _gaussian_ returns

exp(-(x - mean)^2 / 4. / sigma^2)

which has a FWHM of sqrt(2) \* 2.355 sigma (contradiction). 

If you replace the 4 in the first divition by 2 you get exactly what I have in the equation in the document
