### ISSUE TITLE
Include plots

### ISSUE THREAD

**Issue by ezbc** [caverac/agd-doc#4]
For the simple examples, in 3.1.2 we should include the fitted plot.

**Comment by ezbc** [comment]
Include png files instead of code to make plots.

**Comment by ezbc** [comment]
Current figures are PDFs, which work well for Latex. However the HTML compiler for Sphinx does not show PDFs inline.

@cemurray3 can you use PNG filetypes for the figures?

**Comment by cmurray-astro** [comment]
please add png figures for your section which are easier to load on html

**Comment by caverac** [comment]
Done
