### ISSUE TITLE
Latex Compilation Error

### ISSUE THREAD

**Issue by ezbc** [caverac/agd-doc#8]
I'm getting a Latex compilation error (Bad math environment delimiter) which I can't trace to any specific file. Perhaps the problem is within the title of a section? Below is the error:

! LaTeX Error: Bad math environment delimiter.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.17 ...> to continue without it.}}{12}{chapter.5}

**Comment by cmurray-astro** [comment]
Probably in the tutorial (chapter 5). Sorry. I may have messed some things
up by including python scripts for building plots (wasn't sure the best way
to include plots...)

**Comment by caverac** [comment]
Did you guys change something else? because I can compile no problem
